// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, created_at, updated_at, email)
VALUES (
    gen_random_uuid(), -- generate a unique id
    NOW(),             -- current time
    NOW(),             -- current time
    $1                 -- gen code will input email
)
RETURNING id, create_at, updated_at, email
`

// users.sql
func (q *Queries) CreateUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreateAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
